spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1.0/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1.0/**
        - id: NEWS-SERVICE
          uri: lb://NEWS-SERVICE
          predicates:
            - Path=/api/v1.0/**             
        - id: WISHLIST-SERVICE
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/api/v1.0/**